<a href="https://colab.research.google.com/github/harshskadam31/python_practice/blob/main/data_analysis_with_python/pandas_practice_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1u3s_P7kQ6OPJAoGQd587zzrLJHBwh9fy')

# Assignment 3 - Pandas Data Analysis Practice

*This assignment is a part of the course ["Data Analysis with Python: Zero to Pandas"](https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas)*

In this assignment, you'll get to practice some of the concepts and skills covered this tutorial: https://jovian.ml/aakashns/python-pandas-data-analysis

As you go through this notebook, you will find a **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end.

Some things to keep in mind:

* Make sure to run all the code cells, otherwise you may get errors like `NameError` for undefined variables.
* Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
* In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**.
* Since you'll be using a temporary online service for code execution, save your work by running `jovian.commit` at regular intervals.
* Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.

You can make submissions on this page: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-3-pandas-practice

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/assignment-3-pandas-practice/11225/3 . You can get help with errors or ask for hints, describe your approach in simple words, link to documentation, but **please don't ask for or share the full working answer code** on the forum.


## How to run the code and save your work

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on [mybinder.org](https://mybinder.org), a free online service for running Jupyter notebooks.

Before staring the assignment, let's save a snapshot of the assignment to your Jovian.ml profile, so that you can access it later, and continue your work.

In [ ]:
import jovian

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

In [ ]:
# Run the next line to install Pandas
!pip install pandas --upgrade

Requirement already up-to-date: pandas in /usr/local/lib/python3.6/dist-packages (1.1.2)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.18.5)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
import pandas as pd

In [ ]:
import os

os.listdir()

['.config', 'sample_data']

In [3]:
from google.colab import files
uploaded = files.upload()

Saving countries.csv to countries.csv

In this assignment, we're going to analyze an operate on data from a CSV file. Let's begin by downloading the CSV file.

Let's load the data from the CSV file into a Pandas data frame.

In [4]:
countries_df = pd.read_csv('countries.csv')

In [ ]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

**Q: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [17]:
# num_countries = ???
num_countries = countries_df.shape

In [18]:
print("there are {} countries in the dataset.".format(num_countries[0]))

there are 210 countries in the dataset.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [15]:
# continents = ???
continents = countries_df['continent'].unique()

In [16]:
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: What is the total population of all the countries listed in this dataset?**

In [11]:
# total_population = ???
total_population=countries_df['population'].sum()

In [12]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

In [13]:
print('The total population is {:,.2f} people.'.format((total_population)))

The total population is 7,757,980,095.00 people.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: (Optional) What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [6]:
total_population = countries_df['population']
life_expectancy = countries_df['life_expectancy']
total_life_expectancy = (total_population * life_expectancy).sum() / total_population.sum()

In [10]:
print('Expectancy across in the world is {} years old.'.format(total_life_expectancy))

Expectancy across in the world is 72.72165193409664 years old.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [20]:
# most_populous_df = ???
most_populous_df = countries_df.sort_values(by="population", ascending=False).head(10)

In [ ]:
most_populous_df.head(10)

       population       location
41   1.439324e+09          China
90   1.380004e+09          India
199  3.310026e+08  United States
91   2.735236e+08      Indonesia
145  2.208923e+08       Pakistan
27   2.125594e+08         Brazil
141  2.061396e+08        Nigeria
15   1.646894e+08     Bangladesh
157  1.459345e+08         Russia
125  1.289328e+08         Mexico

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [21]:
# countries_df['gdp'] = ???
countries_df['gdp'] = (countries_df.population) * (countries_df.gdp_per_capita)

In [22]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: (Optional) Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [28]:
countries_lowest_gdp = countries_df[countries_df['population'] > 100000000][['location', 'gdp_per_capita', 'gdp']].sort_values(by='gdp_per_capita', ascending=True).head(10)

In [29]:
countries_lowest_gdp = countries_lowest_gdp.sort_values(['gdp_per_capita'], ascending=True)
countries_lowest_gdp.head(10)

        location  gdp_per_capita           gdp
63      Ethiopia        1729.927  1.988786e+11
15    Bangladesh        3523.984  5.803628e+11
145     Pakistan        5034.708  1.112128e+12
141      Nigeria        5338.454  1.100467e+12
90         India        6426.674  8.868838e+12
151  Philippines        7599.188  8.327273e+11
58         Egypt       10550.206  1.079649e+12
91     Indonesia       11188.744  3.060386e+12
27        Brazil       14103.452  2.997821e+12
41         China       15308.712  2.203419e+13

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [32]:
# country_counts_df = ???
country_counts_df=countries_df[['continent', 'location']].groupby('continent', as_index=False).count()

In [31]:
country_counts_df

       continent  location
0         Africa        55
1           Asia        47
2         Europe        51
3  North America        36
4        Oceania         8
5  South America        13

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [33]:
# continent_populations_df = ???
continent_populations_df = countries_df.groupby('continent')[['population']].sum()

In [ ]:
continent_populations_df

                 population
continent
Africa         1.339424e+09
Asia           4.607388e+09
Europe         7.485062e+08
North America  5.912425e+08
Oceania        4.095832e+07
South America  4.304611e+08

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [35]:
from google.colab import files
uploaded = files.upload()

Saving covid-countries-data.csv to covid-countries-data.csv

In [36]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [ ]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**Q: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [37]:
# total_tests_missing = ???
total_tests_missing = covid_data_df['total_tests'].isna().sum()

In [38]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

Let's merge the two data frames, and compute some more metrics.

**Q: Merge `countries_df` with `covid_data_df` on the `location` column.**

*Hint: Use the `.merge` method on `countries_df`.

In [39]:
# combined_df = ???
combined_df = covid_data_df.merge(countries_df,on='location')

In [40]:
combined_df

,location,total_cases,total_deaths,total_tests,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,38243.0,1409.0,NaN,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,9728.0,296.0,NaN,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,45158.0,1525.0,NaN,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,1199.0,53.0,NaN,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,2729.0,109.0,NaN,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,1046.0,35.0,261004.0,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,766.0,1.0,NaN,Africa,597330.0,70.26,NaN,NaN,NaN
207,Yemen,1976.0,571.0,NaN,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10
208,Zambia,12415.0,292.0,NaN,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,6638.0,206.0,97272.0,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [41]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [42]:
# combined_df['cases_per_million'] = ???
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [43]:
# combined_df['deaths_per_million'] = ???
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [ ]:
combined_df

           location  total_cases  ...  cases_per_million  deaths_per_million
0       Afghanistan      38243.0  ...         982.394806           36.194710
1           Albania       9728.0  ...        3380.359997          102.856349
2           Algeria      45158.0  ...        1029.804468           34.776824
3           Andorra       1199.0  ...       15518.022390          685.950948
4            Angola       2729.0  ...          83.033462            3.316470
..              ...          ...  ...                ...                 ...
205         Vietnam       1046.0  ...          10.745996            0.359570
206  Western Sahara        766.0  ...        1282.373228            1.674116
207           Yemen       1976.0  ...          66.250993           19.144391
208          Zambia      12415.0  ...         675.317108           15.883415
209        Zimbabwe       6638.0  ...         446.614587           13.859989

[210 rows x 13 columns]

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [44]:
# highest_tests_df = ???
highest_tests_df = combined_df.sort_values('tests_per_million', ascending=False)

In [46]:
highest_tests_df.head(10)

,location,total_cases,total_deaths,total_tests,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,tests_per_million,cases_per_million,deaths_per_million
197,United Arab Emirates,71540.0,387.0,7177430.0,Asia,9890400.0,77.97,1.200,67293.483,6.655595e+11,725696.635121,7233.276713,39.128852
14,Bahrain,52440.0,190.0,1118837.0,Asia,1701583.0,77.29,2.000,43290.705,7.366273e+10,657527.137965,30818.361490,111.660730
115,Luxembourg,7928.0,124.0,385820.0,Europe,625976.0,82.25,4.510,94277.965,5.901574e+10,616349.508607,12665.022301,198.090662
122,Malta,1931.0,13.0,188539.0,Europe,441539.0,82.53,4.485,36513.323,1.612206e+10,427004.183096,4373.339614,29.442473
53,Denmark,17195.0,626.0,2447911.0,Europe,5792203.0,80.90,2.500,46682.515,2.703946e+11,422621.755488,2968.645954,108.076323
96,Israel,122539.0,969.0,2353984.0,Asia,8655541.0,82.97,2.990,33132.320,2.867782e+11,271962.665303,14157.289533,111.951408
89,Iceland,2121.0,10.0,88829.0,Europe,341250.0,82.99,2.910,46482.958,1.586231e+10,260304.761905,6215.384615,29.304029
157,Russia,1005000.0,17414.0,37176827.0,Europe,145934460.0,72.58,8.050,24765.954,3.614206e+12,254750.159763,6886.653091,119.327539
199,United States,6114406.0,185744.0,83898416.0,North America,331002647.0,78.86,2.770,54225.446,1.794877e+13,253467.507769,18472.377957,561.155633
10,Australia,25923.0,663.0,6255797.0,Oceania,25499881.0,83.44,3.840,44648.710,1.138537e+12,245326.517406,1016.592979,26.000121

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [47]:
# highest_cases_df = ???
highest_cases_df = combined_df.sort_values('cases_per_million', ascending=False)

In [48]:
highest_cases_df.head(10)

,location,total_cases,total_deaths,total_tests,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,tests_per_million,cases_per_million,deaths_per_million
155,Qatar,119206.0,199.0,634745.0,Asia,2881060.0,80.23,1.20,116935.600,3.368985e+11,220316.480740,41375.743650,69.071800
14,Bahrain,52440.0,190.0,1118837.0,Asia,1701583.0,77.29,2.00,43290.705,7.366273e+10,657527.137965,30818.361490,111.660730
147,Panama,94084.0,2030.0,336345.0,North America,4314768.0,78.51,2.30,22267.037,9.607710e+10,77952.047480,21805.112117,470.477208
40,Chile,414739.0,11344.0,2458762.0,South America,19116209.0,80.18,2.11,22767.037,4.352194e+11,128621.841287,21695.671982,593.423100
162,San Marino,735.0,42.0,NaN,Europe,33938.0,84.97,3.80,56861.470,1.929765e+09,NaN,21657.139490,1237.550828
9,Aruba,2211.0,12.0,NaN,North America,106766.0,76.29,NaN,35973.781,3.840777e+09,NaN,20708.839893,112.395332
105,Kuwait,86478.0,535.0,621616.0,Asia,4270563.0,75.49,2.00,65530.537,2.798523e+11,145558.325682,20249.789079,125.276222
150,Peru,663437.0,29259.0,584232.0,South America,32971846.0,76.74,1.60,12236.706,4.034668e+11,17719.117092,20121.318048,887.393445
27,Brazil,3997865.0,123780.0,4797948.0,South America,212559409.0,75.88,2.20,14103.452,2.997821e+12,22572.268255,18808.224105,582.331314
199,United States,6114406.0,185744.0,83898416.0,North America,331002647.0,78.86,2.77,54225.446,1.794877e+13,253467.507769,18472.377957,561.155633

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**Q: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [49]:
# highest_deaths_df = ???
highest_deaths_df = combined_df.sort_values('deaths_per_million', ascending=False)

In [50]:
highest_deaths_df.head(10)

,location,total_cases,total_deaths,total_tests,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,tests_per_million,cases_per_million,deaths_per_million
162,San Marino,735.0,42.0,NaN,Europe,33938.0,84.97,3.80,56861.470,1.929765e+09,NaN,21657.139490,1237.550828
150,Peru,663437.0,29259.0,584232.0,South America,32971846.0,76.74,1.60,12236.706,4.034668e+11,17719.117092,20121.318048,887.393445
18,Belgium,85817.0,9898.0,2281853.0,Europe,11589616.0,81.63,5.64,42658.576,4.943965e+11,196887.713967,7404.645676,854.040375
3,Andorra,1199.0,53.0,NaN,Europe,77265.0,83.73,NaN,NaN,NaN,NaN,15518.022390,685.950948
177,Spain,479554.0,29194.0,6416533.0,Europe,46754783.0,83.56,2.97,34272.360,1.602397e+12,137238.001939,10256.790198,624.406705
198,United Kingdom,338676.0,41514.0,13447568.0,Europe,67886004.0,81.32,2.54,39753.244,2.698689e+12,198090.434075,4988.892850,611.525168
40,Chile,414739.0,11344.0,2458762.0,South America,19116209.0,80.18,2.11,22767.037,4.352194e+11,128621.841287,21695.671982,593.423100
97,Italy,271515.0,35497.0,5214766.0,Europe,60461828.0,83.51,3.18,35220.084,2.129471e+12,86248.897403,4490.684602,587.097697
27,Brazil,3997865.0,123780.0,4797948.0,South America,212559409.0,75.88,2.20,14103.452,2.997821e+12,22572.268255,18808.224105,582.331314
182,Sweden,84532.0,5820.0,NaN,Europe,10099270.0,82.80,2.22,46949.283,4.741535e+11,NaN,8370.109919,576.279276

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**(Optional) Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [57]:
top10_cases = highest_cases_df.head(10)
top10_deaths = highest_deaths_df.head(10)

common_countries = top10_cases[top10_cases['location'].isin(top10_deaths['location'])]
print(common_countries)

       location  total_cases  total_deaths  total_tests      continent  \
40        Chile     414739.0       11344.0    2458762.0  South America
162  San Marino        735.0          42.0          NaN         Europe
150        Peru     663437.0       29259.0     584232.0  South America
27       Brazil    3997865.0      123780.0    4797948.0  South America

      population  life_expectancy  hospital_beds_per_thousand  gdp_per_capita  \
40    19116209.0            80.18                        2.11       22767.037
162      33938.0            84.97                        3.80       56861.470
150   32971846.0            76.74                        1.60       12236.706
27   212559409.0            75.88                        2.20       14103.452

              gdp  tests_per_million  cases_per_million  deaths_per_million
40   4.352194e+11      128621.841287       21695.671982          593.423100
162  1.929765e+09                NaN       21657.139490         1237.550828
150  4.034668e+11       17719.117092       20121.318048          887.393445
27   2.997821e+12       22572.268255       18808.224105          582.331314

In [58]:
highest_tests_df.location

197    United Arab Emirates
14                  Bahrain
115              Luxembourg
122                   Malta
53                  Denmark
               ...
203                 Vatican
204               Venezuela
206          Western Sahara
207                   Yemen
208                  Zambia
Name: location, Length: 210, dtype: object

In [59]:
highest_cases_df.location

155         Qatar
14        Bahrain
147        Panama
40          Chile
162    San Marino
          ...
33       Cambodia
205       Vietnam
187      Tanzania
107          Laos
87      Hong Kong
Name: location, Length: 210, dtype: object

In [ ]:
highest_cases_df['location'].equals(highest_tests_df['location'])

False

In [ ]:
set(highest_cases_df['location']).intersection(set(highest_tests_df['location']))

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

**(Optional) Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [ ]:
import jovian

In [ ]:
jovian.commit(project='pandas-practice-assignment', environment=None)

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Committed successfully! https://jovian.ml/masedos/pandas-practice-assignment

'https://jovian.ml/masedos/pandas-practice-assignment'

## Submission

Congratulations on making it this far! You've reached the end of this assignment, and you just completed your first real-world data analysis problem. It's time to record one final version of your notebook for submission.

Make a submission here by filling the submission form: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-3-pandas-practice

Also make sure to help others on the forum: https://jovian.ml/forum/t/assignment-3-pandas-practice/11225/2